name: Assertions and static report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site https://uatesika.tiendabelcorp.com.pe/ --no-cache --mobile --throttle --build-static
      - uses: actions/upload-artifact@v3
        with:
          name: unlighthouse
          path: .unlighthouse

      - name: Deploy
        run: netlify deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          # NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_UAT_PE_OLD }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_UAT_EXPERIMENTAL }}
